"""empty message

Revision ID: 74edbfd3cbc8
Revises: 8272b766b96f
Create Date: 2023-06-01 05:16:40.684581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74edbfd3cbc8'
down_revision = '8272b766b96f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_mobile', sa.String(length=20), nullable=False))
        batch_op.drop_column('mobile_phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobile_phone', sa.VARCHAR(length=20), nullable=False))
        batch_op.drop_column('phone_mobile')

    # ### end Alembic commands ###
