"""empty message

Revision ID: 99f6fea687ca
Revises: 74edbfd3cbc8
Create Date: 2023-06-08 05:21:16.988399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99f6fea687ca'
down_revision = '74edbfd3cbc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('block_chain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prev_hash', sa.String(length=300), nullable=True),
    sa.Column('nonce', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=True),
    sa.Column('send_addr', sa.String(length=300), nullable=True),
    sa.Column('recv_addr', sa.String(length=300), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['block_chain.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('update_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('private_key', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('public_key', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('blockchain_addr', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('blockchain_addr')
        batch_op.drop_column('public_key')
        batch_op.drop_column('private_key')
        batch_op.drop_column('update_date')
        batch_op.drop_column('create_date')

    op.drop_table('transaction')
    op.drop_table('block_chain')
    # ### end Alembic commands ###
